version: 2
jobs:
    build:
        working_directory: ~/technical-analysis
        docker:
            - image: circleci/ruby:2.3.6
        steps:
            - checkout

            # Bundle install dependencies
            - run: bundle install

            # Run the tests
            - run: bundle exec rspec
